### ISSUE TITLE
Build出错

### ISSUE THREAD

**Issue by GuoYunZheSE** [ifzc/KeJian.Core.Api#2]
> Centos8

输入`dotnet ef migrations add Initial`后，显示
`Unable to create an object of type 'DefaultDbContext'. For the different patterns supported at design time, see https://go.microsoft.com/fwlink/?linkid=851728`
按照StackOverflow所说添加了默认构造函数
结果报
`No database provider has been configured for this DbContext.`
请问是因为我的配置文件的问题吗？
> appsettings.Demo.json

```
{
  "ConnectionStrings": {
    "DefaultConnection": "Database='kejian';Data Source=127.0.0.1;User ID=root;Password=123456;CharSet=utf8;SslMode=None"
  },
  "JwtSecurityOption": {
    "SigningKey": "709AB925-E1A3-0F00-8E2D-6F9AE251378C"
  }
}
```

**Comment by ifzc** [comment]
你好，白天没看到，久等😊

给你提供以下找问题思路：
1. 如果是 CodeFirst 模式来创建数据库：
    首先删除 Migrations 文件夹下面的所有文件（这些文件是EF在执行 Add-Migration Initial 命令产生的，也相当于是每一次表结构变化的记录，不删除的话应该直接执行 Update-Database）
    那么打开程序包管理控制台，目标项目设置为 KeJian.Core.EntityFramework
    这时运行 Add-Migration Initial EF会在 Migrations 生成初始化文件
    运行 Update-Database 更新到数据库
     
2. dotnet ef migrations add Initial  等同于 Add-Migration Initial 
    dotnet ef database update 等同于 Update-Database
    同样要在 KeJian.Core.EntityFramework 项目下执行

3. 如果是直接生成SQL语句（一些生产环境开发者没有直接操作数据库的权限）
    首先删除 Migrations 文件夹下面的所有文件
    然后执行 Script-Migration

4. 这个是针对的MySql，针对SqlServer的有小的差异

5. My SQL 部分版本（有坑），不允许程序 CodeFirst 直接创建数据库，需要先创建个数据库，其他不变

6. 不确定会不会是这个 Database='kejian' 一般不需要单引号

比较啰嗦，互相学习😊

**Comment by GuoYunZheSE** [comment]
好的，谢谢，因为在centos上进行build，然后同时mac上没有PM就给我造成了很大的困扰，最后我选择了先在本地Publish再导出.dll到服务器方法解决了这个问题。
