### ISSUE TITLE
为啥有一些接口是404呢

### ISSUE THREAD

**Issue by nk-akun** [ifzc/KeJian.Core.Api#6]
/api/Team/GetTeamAll
/api/Honor/GetHonorAll
/api/Enterprise/GetEnterpriseAll

还有其他的几个，前端访问本地5001后端端口，都是404呢
后端项目中也没有搜索到相关接口

**Comment by ifzc** [comment]
这个后端接口也是重构版的，重构前是.Net Framework ,重构成Core之后接口路由改的更加 restful 和简单了一点，比如这个 /api/Team/GetTeamAll 换成了 /api/Team 具体的你可以打开 /swagger 看一下

**Comment by nk-akun** [comment]
> 这个后端接口也是重构版的，重构前是.Net Framework ,重构成Core之后接口路由改的更加 restful 和简单了一点，比如这个 /api/Team/GetTeamAll 换成了 /api/Team 具体的你可以打开 /swagger 看一下

我需要挨个更改一下前端代码里的后端url吗？将/api/Team/GetTeamAll 换成 /api/Team ？

**Comment by nk-akun** [comment]
另外请教一下，对于下面这段代码：
```C#
  /// <summary>
  ///     新闻动态列表
  /// </summary>
  /// <param name="type">类型：1：新闻资讯 2：行业动态</param>
  /// <param name="count">条数</param>
  /// <returns></returns>
  [HttpGet("/Search")]
  public async Task<List<News>> GetAsync(int type, int count)
  {
      
      Trace.WriteLine(type);
      Trace.WriteLine(count);
      return await _application.GetAsync(type, count);
  }
```

我通过浏览器访问http://localhost:5001/api/news/Search?type=1&count=2
会报：
```json
  "result": {
    "type": "https://tools.ietf.org/html/rfc7231#section-6.5.1",
    "title": "One or more validation errors occurred.",
    "status": 400,
    "traceId": "|583f1e1a-4974e477a59fb589.",
    "errors": {
      "id": [
        "The value 'Search' is not valid."
      ]
    }
  },
  "isSuccess": true,
  "errorCode": 400,
  "message": "",
  "operationId": "|583f1e1a-4974e477a59fb589."
}
```

为啥呢，真奇怪

**Comment by nk-akun** [comment]
而且我发现，前端访问的登录接口为/api/User/Login?strUser=admin&strPwd=admin
后端Login方法却在Account里，User中没有对应方法
啊，这咋整又
