### ISSUE TITLE
能不能来个sqlserver 或者sqlite版本

### ISSUE THREAD

**Issue by ctx1103449953** [ifzc/KeJian.Core.Api#8]
能不能来个sqlserver 或者sqlite版本

**Comment by ifzc** [comment]
你可以尝试自己改下，换成EF对应的SqlServer版本就可以了，非常快就可以完成，我也提供了建表语句，让GPT把它改成SqlServer就可以了

**Comment by ctx1103449953** [comment]
已收到！！

**Comment by ctx1103449953** [comment]
你好，你这里的方法和前端的获取的方法都对不上了。好多东西都要改，或者说能不能发个完整版本的。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ifzc/KeJian.Core.Api"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年5月7日(星期二) 凌晨0:23
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [ifzc/KeJian.Core.Api] 能不能来个sqlserver 或者sqlite版本 (Issue #8)





 
你可以尝试自己改下，换成EF对应的SqlServer版本就可以了，非常快就可以完成，我也提供了建表语句，让GPT把它改成SqlServer就可以了

**Comment by ifzc** [comment]
这个版本是我想学习下升级架构出的，没有去做对接，原版是和页面对接完全一致的可以看这个，我归档起来的：https://github.com/ifzc/ShkjemApi

**Comment by ifzc** [comment]
老版本的确实不太推荐，因为都还不是Core的， 老版本还是 SqlService 的

**Comment by ctx1103449953** [comment]
好的，感谢，这个企业站样式也很漂亮




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ifzc/KeJian.Core.Api"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年5月10日(星期五) 中午1:32
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [ifzc/KeJian.Core.Api] 能不能来个sqlserver 或者sqlite版本 (Issue #8)





 
这个版本是我想学习下升级架构出的，没有去做对接，原版是和页面对接完全一致的可以看这个，我归档起来的：https://github.com/ifzc/ShkjemApi
